--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/henri/Pictures/Wallpapers/VinlandSagaWater.png"

-- Special
background="#0E1218"
foreground="#94c5d5"
cursor="#94c5d5"

-- Colors
color0="#0E1218"
color1="#2A505C"
color2="#124A70"
color3="#585A5C"
color4="#955137"
color5="#1C6896"
color6="#517789"
color7="#94c5d5"
color8="#678995"
color9="#2A505C"
color10="#124A70"
color11="#585A5C"
color12="#955137"
color13="#1C6896"
color14="#517789"
color15="#94c5d5"
