# Shell variables
# Generated by 'wal'
wallpaper='/home/henri/Pictures/Wallpapers/BlueClouds2.jpg'

# Special
background='#13214a'
foreground='#e0edf2'
cursor='#e0edf2'

# Colors
color0='#13214a'
color1='#2B72CC'
color2='#4298D9'
color3='#609ED9'
color4='#94ADD0'
color5='#A9D9F0'
color6='#C7DAEB'
color7='#e0edf2'
color8='#9ca5a9'
color9='#2B72CC'
color10='#4298D9'
color11='#609ED9'
color12='#94ADD0'
color13='#A9D9F0'
color14='#C7DAEB'
color15='#e0edf2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
