# Shell variables
# Generated by 'wal'
wallpaper='/home/henri/Pictures/Wallpapers/VinlandSagaWater.png'

# Special
background='#0E1218'
foreground='#94c5d5'
cursor='#94c5d5'

# Colors
color0='#0E1218'
color1='#2A505C'
color2='#124A70'
color3='#585A5C'
color4='#955137'
color5='#1C6896'
color6='#517789'
color7='#94c5d5'
color8='#678995'
color9='#2A505C'
color10='#124A70'
color11='#585A5C'
color12='#955137'
color13='#1C6896'
color14='#517789'
color15='#94c5d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
