--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/henri/Pictures/Wallpapers/BlueClouds2.jpg"

-- Special
background="#13214a"
foreground="#e0edf2"
cursor="#e0edf2"

-- Colors
color0="#13214a"
color1="#2B72CC"
color2="#4298D9"
color3="#609ED9"
color4="#94ADD0"
color5="#A9D9F0"
color6="#C7DAEB"
color7="#e0edf2"
color8="#9ca5a9"
color9="#2B72CC"
color10="#4298D9"
color11="#609ED9"
color12="#94ADD0"
color13="#A9D9F0"
color14="#C7DAEB"
color15="#e0edf2"
